# Generated by Django 3.0.1 on 2020-10-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterilization_date', models.CharField(max_length=40, null=True, verbose_name='Дата стерилизации')),
                ('doctor', models.CharField(max_length=50, null=True, verbose_name='ФИО вет врача')),
                ('socialized', models.BinaryField(null=True, verbose_name='Социализировано (да/нет)')),
            ],
        ),
        migrations.CreateModel(
            name='Animal_move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_add_date', models.DateField(null=True, verbose_name='Дата поступления в приют')),
                ('shelter_add_act', models.CharField(max_length=100, null=True, verbose_name='Акт №')),
                ('shelter_leave_date', models.DateField(null=True, verbose_name='Дата выбития из приюта')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Причина выбытия')),
                ('shelter_leave_act', models.CharField(max_length=20, null=True, verbose_name='Акт/договор №')),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_card', models.CharField(max_length=20, null=True, verbose_name='Карточка учета')),
                ('kind', models.CharField(max_length=7, null=True, verbose_name='Вид')),
                ('year_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('weight', models.IntegerField(null=True, verbose_name='Вес')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='Кличка')),
                ('sex', models.BinaryField(choices=[('M', 'Кабель'), ('Ж', 'Сучка')], verbose_name='Пол')),
                ('breed', models.CharField(max_length=50, null=True, verbose_name='Порода')),
                ('color', models.CharField(max_length=20, null=True, verbose_name='Цвет')),
                ('wool', models.CharField(max_length=10, null=True, verbose_name='Шерсть')),
                ('ears', models.CharField(max_length=20, null=True, verbose_name='Уши')),
                ('tail', models.CharField(max_length=20, null=True, verbose_name='Хвост')),
                ('size', models.CharField(max_length=10, null=True, verbose_name='Размер')),
                ('signs', models.BinaryField(null=True, verbose_name='Особые приметы')),
                ('area', models.IntegerField(null=True, verbose_name='Вольер №')),
            ],
        ),
        migrations.CreateModel(
            name='Catch_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_of_adm_data', models.DateField(null=True, verbose_name='Акт о поступлении животного, дата')),
                ('district', models.CharField(max_length=10, null=True, verbose_name='Административный округ')),
                ('catch_act', models.CharField(max_length=20, null=True, verbose_name='Акт отлова №')),
                ('catch_address', models.CharField(max_length=100, null=True, verbose_name='Адоес места отлова')),
            ],
        ),
        migrations.CreateModel(
            name='Ecto_endo_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecto_endo_data', models.DateField(null=True, verbose_name='Дата')),
                ('drugs_name', models.CharField(max_length=50, null=True, verbose_name='Название препарата')),
                ('drugs_dose', models.IntegerField(null=True, verbose_name='Доза')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(null=True, verbose_name='Дата осмотра')),
                ('anamnez', models.CharField(max_length=50, null=True, verbose_name='Анамнез')),
            ],
        ),
        migrations.CreateModel(
            name='New_owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50, null=True, verbose_name='Юридическое лицо')),
                ('trustee', models.CharField(max_length=50, null=True, verbose_name='ФИО опекунов')),
                ('individual', models.CharField(max_length=50, null=True, verbose_name='Физическое лицо')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_address', models.CharField(max_length=100, null=True, verbose_name='Адрес приюта')),
                ('organization_name', models.CharField(max_length=20, null=True, verbose_name='Эксплотирующая организация')),
                ('org_lead_name', models.CharField(max_length=50, null=True, verbose_name='ФИО руководителя приюта')),
                ('worker_name', models.CharField(max_length=50, null=True, verbose_name='ФИО сотрудника по уходу за животным')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_date', models.CharField(max_length=100, null=True, verbose_name='Дата')),
                ('vac_type', models.CharField(max_length=100, null=True, verbose_name='Вид вакцины')),
                ('vac_no', models.CharField(max_length=100, null=True, verbose_name='№ серии')),
            ],
        ),
    ]
